
import ProviderText from '@/components/ProviderText'
import './globals.css'
import { Inter } from 'next/font/google'
import Cursor from '@/components/Cursor'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      
        
       <ProviderText>  <Cursor/>
       {children}
       </ProviderText>
        
        </body>
    </html>
  )
}
